version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - FLASK_ENV=development
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./apps/backend:/app
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
