services:
  # Backend Service
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./apps/backend/Dockerfile
    dockerContext: ./apps/backend
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health
    disk:
      name: backend-disk
      sizeGB: 1
      mountPath: /app/data

  # Frontend Service
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./apps/frontend/Dockerfile
    dockerContext: ./apps/frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://your-app-backend.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /api/health